### ISSUE TITLE
unable to load Seurat

### ISSUE THREAD

**Issue by jingzhizhu** [MonashBioinformaticsPlatform/rocker-ultra#2]
I was able to successfully start Rstudio server in our Linux cluster by following your guide. However, I am getting this error

> library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/rgeos/libs/rgeos.so':
  libgeos_c.so.1: cannot open shared object file: No such file or directory

I was able to copy the libgeos_c.so.1 from another machine, but I am getting this error

> dyn.load("/home/user/libgeos/libgeos-3.7.1.so")
> dyn.load("/home/user/libgeos/libgeos_c.so.1")
> library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/rgeos/libs/rgeos.so':
  /usr/local/lib/R/site-library/rgeos/libs/rgeos.so: undefined symbol: GEOSCoverageUnion_r

I know it is a problem of the singularity image your script is pulling from by default. Do you have idea how to resolve this kind of issue?

Thanks!

**Comment by jingzhizhu** [comment]
If I start rstudio.sh with this way, then the problem seems to go away

IMAGE=pansapiens/rocker-seurat:4.1.1-4.0.4 ./rstudio.sh

**Comment by pansapiens** [comment]
More recent images also seem to be working fine. Thanks for reporting, I'll close this.
